# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PopupManagerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PopupManagerDemo
  pod 'FGPopupScheduler-Swift'

  target 'PopupManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PopupManagerDemoUITests' do
    # Pods for testing
  end

end
